In [1]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [171]:
data=pd.read_csv('/content/MY_last_data.csv',encoding='ISO-8859-1')
data

name                category  \
0              The Museum of Egyptian Antiquities      Speciality Museums   
1                                    Luxor Museum         History Museums   
2                         Bibliotheca Alexandrina             Art Museums   
3                                 Mini Egypt Park      Speciality Museums   
4                                   Nubian Museum         History Museums   
5   National Museum of Egyptian Civilization NEMC         History Museums   
6                               The Coptic Museum             Art Museums   
7                          Karnak Open Air Museum         History Museums   
8                            Royal Jewelry Museum      Speciality Museums   
9                          Museum of Islamic Arts       Religious Museums   
10                     Alexandria National Museum         History Museums   
11                                King Tut Museum         History Museums   
12                         Sharm El-Sheikh Museum         History Museums   
13                                 Imhotep Museum      Speciality Museums   
14                          El Alamein War Museum        Military Museums   
15                                Hurghada Museum             Art Museums   
16                                Military Museum        Military Museums   
17                      Port Said Military Museum        Military Museums   
18                  El Nasr Museum For Modern Art             Art Museums   
19                           The Fine Arts Museum             Art Museums   
20                            Ahmed Shawki Museum      Speciality Museums   
21                      The Grand Egyptian Museum         History Museums   
22                           Abdeen Palace Museum         History Museums   
23                                   Tanta Museum         History Museums   
24                               Kom Ushim Museum  Archaeological Museums   
25                              New Valley Museum        Regional Museums   
26                              Tell Basta Museum  Archaeological Museums   
27                       El Arish National Museum         History Museums   
28                          Kafr El-Sheikh Museum        Regional Museums   
29                            Faiyum Oasis Museum        Regional Museums   
30                          Gayer-Anderson Museum  Historic House Museums   
31                               Beni Suef Museum        Regional Museums   
32                        Wadi El-Natroun Museums        Cultural Museums   
33                         Basilica Church Museum       Religious Museums   
34                                  Coptic Museum       Religious Museums   
35                           Manial Palace Museum  Historic House Museums   
36                                 Saqqara Museum  Archaeological Museums   
37                          Deir el-Bahari Museum  Archaeological Museums   
38                     Museum of Islamic Ceramics      Speciality Museums   
39                           The Egyptian Museum          History Museums   
40                       Egyptian Textiles Museum         History Museums   
41                         The Royal Mummies Hall      Speciality Museums   
42                               The Child Museum        Cultural Museums   
43                           Mummification Museum  Archaeological Museums   
44                             Greco-Roman Museum  Archaeological Museums   
45                  Museum of Modern Egyptian Art             Art Museums   
46                      Prince Mohamed Ali Palace         History Museums   
47                                   Aswan Museum         History Museums   
48                        The Agricultural Museum      Speciality Museums   

                                             Keywords  \
0   king tut, amazing collection, on display, deat...   
1   couple of hours, worth a visit, temples and to...   
2   modern library, ama

In [172]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   name         49 non-null     object 
 1   category     49 non-null     object 
 2   Keywords     49 non-null     object 
 3   Description  49 non-null     object 
 4   State_Name   49 non-null     object 
 5   Raiting      49 non-null     float64
 6   Rank         49 non-null     int64  
dtypes: float64(1), int64(1), object(5)
memory usage: 2.8+ KB


In [173]:
data['category'].value_counts()

category
History Museums           15
Speciality Museums         8
Art Museums                6
Archaeological Museums     6
Regional Museums           4
Religious Museums          3
Military Museums           3
Historic House Museums     2
Cultural Museums           2
Name: count, dtype: int64

In [175]:
data['State_Name'].value_counts()

State_Name
Cairo                     16
Alexandria                 5
Giza                       5
Luxor                      4
Hurghada                   2
Aswan                      2
Sharm El Sheikh            2
Port Said                  2
Fayoum                     2
Beheira                    2
Kafr El-Sheikh             1
Beni Suef                  1
Tanta                      1
North Sinai                1
Sharkia                    1
New Valley Governorate     1
Alexanria                  1
Name: count, dtype: int64

In [176]:
data['Tags']=data['category']+','+data['Keywords']+','+data['Description']+','+data['State_Name']

data['Tags'][0]

'Speciality Museums,king tut, amazing collection, on display, death mask, royal mummies, gold mask, take photos, tahrir square, ancient, egypt, egyptian, pounds, exhibits, mummy, camera, sarcophagus, tuts, coffin, contents, thousands, signage, jewelry, kingdom, civilization, highlights,This famous museum houses the worldâ\x80\x99s largest collection of ancient Egyption artifacts (more than 120,000 items on display) featuring\r\nthe famous Tutankhamun collection with its beautiful gold death mask and sarcophagus and the royal Mummy room, which houses an additional eleven Pharaonic dignitaries.,Cairo'

In [177]:
data['Tags'] = data['Tags'].apply(lambda x:x.lower() )

data.head()

name            category  \
0  The Museum of Egyptian Antiquities  Speciality Museums   
1                        Luxor Museum     History Museums   
2             Bibliotheca Alexandrina         Art Museums   
3                     Mini Egypt Park  Speciality Museums   
4                       Nubian Museum     History Museums   

                                            Keywords  \
0  king tut, amazing collection, on display, deat...   
1  couple of hours, worth a visit, temples and to...   
2  modern library, amazing library, cultural cent...   
3  couple of hours, amazing photos, tour guide, w...   
4  interesting exhibits, chronological order, old...   

                                         Description  State_Name  Raiting  \
0  This famous museum houses the world’s larges...       Cairo      4.5   
1  A museum featuring items found beneath the Lux...       Luxor      4.5   
2  Located near the site of the ancient library o...  Alexandria      4.5   
3  Mini egypt park is a miniature for all egypt i...    Hurghada      4.5   
4  This museum traces the history from the earlie...       Aswan      4.5   

   Rank                                               Tags  
0     2  speciality museums,king tut, amazing collectio...  
1    12  history museums,couple of hours, worth a visit...  
2     3  art museums,modern library, amazing library, c...  
3     4  speciality museums,couple of hours, amazing ph...  
4     5  history museums,interesting exhibits, chronolo...

In [178]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=1000,stop_words='english')

In [179]:
cv.fit_transform(data['Tags']).toarray()

array([[1, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [180]:
cv.fit_transform(data['Tags']).toarray().shape

(49, 844)

In [181]:
vectors = cv.fit_transform(data['Tags']).toarray()

vectors

array([[1, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [182]:
import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [183]:
def stem(text):
    y=[]
    for i in text.split():
        ps.stem(i)

In [184]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [185]:
data['Tags']=data['Tags'].apply(stem)

In [186]:
vectors = cv.fit_transform(data['Tags']).toarray()

vectors

array([[1, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [187]:
from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vectors)

In [188]:
similarity.shape

(49, 49)

In [209]:
import numpy as np
import os
import pickle

if isinstance(vectors, np.ndarray):
    vectors = pd.DataFrame(vectors)

# Create a directory to store the similarity\
os.makedirs('similarity_matrices_2', exist_ok=True)

# Loop all states
for category in data['category'].unique():
    category_filtered_museums = data[data['category'] == category]
    category_vectors = vectors.loc[category_filtered_museums.index]
    category_similarity = cosine_similarity(category_vectors)

    print(f"Category: {category}")
    print(f"Category_vectors shape: {category_vectors.shape}")
    print(f"Category_similarity shape: {category_similarity.shape}")

    filename = os.path.join('similarity_matrices_2', f'similarity_{category.replace(" ", "_")}.pkl')
    with open(filename, 'wb') as f:
        pickle.dump(category_similarity, f)

Category: Speciality Museums
Category_vectors shape: (8, 837)
Category_similarity shape: (8, 8)
Category: History Museums
Category_vectors shape: (15, 837)
Category_similarity shape: (15, 15)
Category: Art Museums
Category_vectors shape: (6, 837)
Category_similarity shape: (6, 6)
Category: Religious Museums
Category_vectors shape: (3, 837)
Category_similarity shape: (3, 3)
Category: Military Museums
Category_vectors shape: (3, 837)
Category_similarity shape: (3, 3)
Category: Archaeological Museums
Category_vectors shape: (6, 837)
Category_similarity shape: (6, 6)
Category: Regional Museums
Category_vectors shape: (4, 837)
Category_similarity shape: (4, 4)
Category: Historic House Museums
Category_vectors shape: (2, 837)
Category_similarity shape: (2, 2)
Category: Cultural Museums
Category_vectors shape: (2, 837)
Category_similarity shape: (2, 2)


In [190]:
data['name'].unique()

array(['The Museum of Egyptian Antiquities', 'Luxor Museum',
       'Bibliotheca Alexandrina', 'Mini Egypt Park', 'Nubian Museum',
       'National Museum of Egyptian Civilization NEMC',
       'The Coptic Museum', 'Karnak Open Air Museum',
       'Royal Jewelry Museum', 'Museum of Islamic Arts',
       'Alexandria National Museum', 'King Tut Museum',
       'Sharm El-Sheikh Museum', 'Imhotep Museum',
       'El Alamein War Museum', 'Hurghada Museum', 'Military Museum',
       'Port Said Military Museum', 'El Nasr Museum For Modern Art',
       'The Fine Arts Museum', 'Ahmed Shawki Museum',
       'The Grand Egyptian Museum', 'Abdeen Palace Museum',
       'Tanta Museum', 'Kom Ushim Museum', 'New Valley Museum',
       'Tell Basta Museum', 'El Arish National Museum',
       'Kafr El-Sheikh Museum', 'Faiyum Oasis Museum',
       'Gayer-Anderson Museum', 'Beni Suef Museum',
       'Wadi El-Natroun Museums', 'Basilica Church Museum',
       'Coptic Museum', 'Manial Palace Museum', 'Saqqar

In [154]:
category_name=data[data['name']=='National Museum of Egyptian Civilization NEMC'].iloc[0].category
category_name

'History Museums'

In [114]:
museum_index = list(data[(data['category'] =='Speciality Museums')].index)
museum_index

[0, 3, 8, 13, 20, 38]

In [116]:
category_name='Speciality Museums'

In [117]:
filename = f'similarity_matrices/similarity_{category_name.replace(" ", "_")}.pkl'
with open(filename, 'rb') as f:
    category_similarity = pickle.load(f)

In [119]:
category_similarity[0]

array([1.        , 0.25339549, 0.30925856, 0.19880668, 0.18386578,
       0.15029153])

In [191]:
category_name=data[data['name']=='National Museum of Egyptian Civilization NEMC'].iloc[0].category
filename = f'similarity_matrices/similarity_{category_name.replace(" ", "_")}.pkl'
with open(filename, 'rb') as f:
    category_similarity = pickle.load(f)


museum_index = data[(data['category'] == category_name) &
                           (data['name'] == 'National Museum of Egyptian Civilization NEMC')].index[0]

local_index = list(data[data['category'] == category_name].index).index(museum_index)
distances = category_similarity[local_index]

# The number of museums that are most similar should not exceed the size of the matrix
num_of_museums = category_similarity.shape[0]
num_of_recommendations = min(num_of_museums, 5)
num_of_recommendations

5

In [210]:
def recommend(museum_name):
    if museum_name not in data['name'].values:
          print(f"Museum named '{museum_name}' not found.")
          return []
    category_name=data[data['name']==museum_name].iloc[0].category
    filename = f'similarity_matrices_2/similarity_{category_name.replace(" ", "_")}.pkl'
    with open(filename, 'rb') as f:
        category_similarity = pickle.load(f)


    museum_index = data[(data['category'] == category_name) &
                           (data['name'] == museum_name)].index[0]

    local_index = list(data[data['category'] == category_name].index).index(museum_index)
    distances = category_similarity[local_index]

    # The number of museums that are most similar should not exceed the size of the matrix
    num_of_museums = category_similarity.shape[0]
    num_of_recommendations = min(num_of_museums, 5)

    # Get an index of the most similar museums (make sure not to go out of range)
    similar_indices = sorted(range(num_of_museums), key=lambda i: distances[i], reverse=True)[1:num_of_recommendations+1]

    category_filtered_museums = data[data['category'] == category_name]
    recommended_museum_names = category_filtered_museums.iloc[similar_indices]['name'].tolist()
    return recommended_museum_names

In [211]:
m=recommend("The Grand Egyptian Museum")
m

['The Egyptian Museum ',
 'El Arish National Museum',
 'Aswan Museum',
 'Tanta Museum',
 'Sharm El-Sheikh Museum']

In [196]:
import pickle

In [197]:
#Converting DF into dictionary for dumping the data

pickle.dump(data,open('museums.pkl','wb'))

In [198]:
data['name'].values

array(['The Museum of Egyptian Antiquities', 'Luxor Museum',
       'Bibliotheca Alexandrina', 'Mini Egypt Park', 'Nubian Museum',
       'National Museum of Egyptian Civilization NEMC',
       'The Coptic Museum', 'Karnak Open Air Museum',
       'Royal Jewelry Museum', 'Museum of Islamic Arts',
       'Alexandria National Museum', 'King Tut Museum',
       'Sharm El-Sheikh Museum', 'Imhotep Museum',
       'El Alamein War Museum', 'Hurghada Museum', 'Military Museum',
       'Port Said Military Museum', 'El Nasr Museum For Modern Art',
       'The Fine Arts Museum', 'Ahmed Shawki Museum',
       'The Grand Egyptian Museum', 'Abdeen Palace Museum',
       'Tanta Museum', 'Kom Ushim Museum', 'New Valley Museum',
       'Tell Basta Museum', 'El Arish National Museum',
       'Kafr El-Sheikh Museum', 'Faiyum Oasis Museum',
       'Gayer-Anderson Museum', 'Beni Suef Museum',
       'Wadi El-Natroun Museums', 'Basilica Church Museum',
       'Coptic Museum', 'Manial Palace Museum', 'Saqqar

In [199]:
pickle.dump(data.to_dict(),open('museums_dict.pkl','wb'))

In [200]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [201]:
# Adding State_Name filter to the app

unique_states_df = pd.DataFrame(data['category'].unique(), columns=['category'])

unique_states_df.to_pickle('category.pkl')

In [205]:
data.to_dict()

{'name': {0: 'The Museum of Egyptian Antiquities',
  1: 'Luxor Museum',
  2: 'Bibliotheca Alexandrina',
  3: 'Mini Egypt Park',
  4: 'Nubian Museum',
  5: 'National Museum of Egyptian Civilization NEMC',
  6: 'The Coptic Museum',
  7: 'Karnak Open Air Museum',
  8: 'Royal Jewelry Museum',
  9: 'Museum of Islamic Arts',
  10: 'Alexandria National Museum',
  11: 'King Tut Museum',
  12: 'Sharm El-Sheikh Museum',
  13: 'Imhotep Museum',
  14: 'El Alamein War Museum',
  15: 'Hurghada Museum',
  16: 'Military Museum',
  17: 'Port Said Military Museum',
  18: 'El Nasr Museum For Modern Art',
  19: 'The Fine Arts Museum',
  20: 'Ahmed Shawki Museum',
  21: 'The Grand Egyptian Museum',
  22: 'Abdeen Palace Museum',
  23: 'Tanta Museum',
  24: 'Kom Ushim Museum',
  25: 'New Valley Museum',
  26: 'Tell Basta Museum',
  27: 'El Arish National Museum',
  28: 'Kafr El-Sheikh Museum',
  29: 'Faiyum Oasis Museum',
  30: 'Gayer-Anderson Museum',
  31: 'Beni Suef Museum',
  32: 'Wadi El-Natroun Museums

In [207]:
%cd ..

/content


In [212]:
!zip -r similarity_matrices_2.zip similarity_matrices_2/

  adding: similarity_matrices_2/ (stored 0%)
  adding: similarity_matrices_2/similarity_Historic_House_Museums.pkl (deflated 19%)
  adding: similarity_matrices_2/similarity_Religious_Museums.pkl (deflated 24%)
  adding: similarity_matrices_2/similarity_Archaeological_Museums.pkl (deflated 30%)
  adding: similarity_matrices_2/similarity_Regional_Museums.pkl (deflated 26%)
  adding: similarity_matrices_2/similarity_Military_Museums.pkl (deflated 22%)
  adding: similarity_matrices_2/similarity_Speciality_Museums.pkl (deflated 32%)
  adding: similarity_matrices_2/similarity_Cultural_Museums.pkl (deflated 18%)
  adding: similarity_matrices_2/similarity_History_Museums.pkl (deflated 37%)
  adding: similarity_matrices_2/similarity_Art_Museums.pkl (deflated 31%)
